<a href="https://colab.research.google.com/github/armaanrathod/EDA-lab-3rd-sem-final/blob/main/exp2_21july.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
df3SE = pd.DataFrame({
    'StudentID': range(31, 41),
    'ScoreSE': np.random.randint(20, 100, size=10)
})
df4SE = pd.DataFrame({
    'StudentID': range(41, 51),
    'ScoreSE': np.random.randint(20, 100, size=10)
})
df3ML = pd.DataFrame({
    'StudentID': range(51, 61),
    'ScoreML': np.random.randint(20, 100, size=10)
})
df4ML = pd.DataFrame({
    'StudentID': range(61, 71),
    'ScoreML': np.random.randint(20, 100, size=10)
})

display(df3SE)
display(df4SE)
display(df3ML)
display(df4ML)

   StudentID  ScoreSE
0         31       29
1         32       99
2         33       26
3         34       87
4         35       66
5         36       59
6         37       46
7         38       81
8         39       70
9         40       38

   StudentID  ScoreSE
0         41       89
1         42       94
2         43       29
3         44       48
4         45       45
5         46       47
6         47       45
7         48       76
8         49       90
9         50       64

   StudentID  ScoreML
0         51       85
1         52       26
2         53       72
3         54       86
4         55       60
5         56       83
6         57       90
7         58       23
8         59       47
9         60       79

   StudentID  ScoreML
0         61       66
1         62       34
2         63       71
3         64       89
4         65       28
5         66       67
6         67       82
7         68       96
8         69       52
9         70       22

In [50]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
df

    StudentID  ScoreML  StudentID  ScoreSE
0         1.0     39.0          9       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          6       44
14       29.0     49.0          8       77
15        2.0     93.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         14       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

In [51]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
df

    StudentID  ScoreSE  ScoreML
0           9       22       52
1          11       66       86
2          13       31       41
3          15       51       77
4          17       71       73
5          19       91       51
6          21       56       86
7          23       32       82
8          25       52       92
9          27       73       23
10         29       92       49
11          2       98       93
12          4       93       44
13          6       44       78
14          8       77       97
15         10       69       87
16         12       56       89
17         14       31       39
18         16       53       43
19         18       78       88
20         20       93       78

In [52]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

    StudentID  ScoreSE  ScoreML
0           9       22     52.0
1          11       66     86.0
2          13       31     41.0
3          15       51     77.0
4          17       71     73.0
5          19       91     51.0
6          21       56     86.0
7          23       32     82.0
8          25       52     92.0
9          27       73     23.0
10         29       92     49.0
11          2       98     93.0
12          4       93     44.0
13          6       44     78.0
14          8       77     97.0
15         10       69     87.0
16         12       56     89.0
17         14       31     39.0
18         16       53     43.0
19         18       78     88.0
20         20       93     78.0
21         22       56      NaN
22         24       77      NaN
23         26       33      NaN
24         28       56      NaN
25         30       27      NaN

In [53]:
display(df.head(10))

print('\nDescriptive statistics for the student DataFrame:')
display(df.describe())

print('\nReshaping scores using StudentID as index:')
df_indexed = df.set_index('StudentID')

df_stacked_scores = df_indexed[['ScoreSE', 'ScoreML']].stack()
print('Stacked scores (Series with MultiIndex):')
display(df_stacked_scores.head())

df_unstacked_scores = df_stacked_scores.unstack()
print('\nUnstacked scores:')
display(df_unstacked_scores.head())

print('\nConcatenating and unstacking score series:')
series_score_se = df_indexed['ScoreSE'].dropna()
series_score_ml = df_indexed['ScoreML'].dropna()

combined_scores_series = pd.concat([series_score_se, series_score_ml], keys=['SE_Scores', 'ML_Scores'])
print('Combined scores (Series with MultiIndex from concatenation):')
display(combined_scores_series.head())

combined_scores_df = combined_scores_series.unstack(level=0)
print('\nUnstacked combined scores:')
display(combined_scores_df.head())

   StudentID  ScoreSE  ScoreML
0          9       22     52.0
1         11       66     86.0
2         13       31     41.0
3         15       51     77.0
4         17       71     73.0
5         19       91     51.0
6         21       56     86.0
7         23       32     82.0
8         25       52     92.0
9         27       73     23.0

Descriptive statistics for the student DataFrame:

       StudentID    ScoreSE    ScoreML
count  26.000000  26.000000  21.000000
mean   17.269231  60.692308  68.952381
std     8.042675  22.930799  22.446550
min     2.000000  22.000000  23.000000
25%    11.250000  45.750000  49.000000
50%    17.500000  56.000000  78.000000
75%    23.750000  77.000000  87.000000
max    30.000000  98.000000  97.000000

Reshaping scores using StudentID as index:
Stacked scores (Series with MultiIndex):

StudentID
9          ScoreSE    22.0
           ScoreML    52.0
11         ScoreSE    66.0
           ScoreML    86.0
13         ScoreSE    31.0
dtype: float64

Unstacked scores:

           ScoreSE  ScoreML
StudentID
9             22.0     52.0
11            66.0     86.0
13            31.0     41.0
15            51.0     77.0
17            71.0     73.0

Concatenating and unstacking score series:
Combined scores (Series with MultiIndex from concatenation):

           StudentID
SE_Scores  9            22.0
           11           66.0
           13           31.0
           15           51.0
           17           71.0
dtype: float64

Unstacked combined scores:

           SE_Scores  ML_Scores
StudentID
2               98.0       93.0
4               93.0       44.0
6               44.0       78.0
8               77.0       97.0
9               22.0       52.0