<a href="https://colab.research.google.com/github/armaanrathod/EDA-lab-3rd-sem-final/blob/main/exp_2_28.07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd

In [ ]:

data = np.arange(10, 25).reshape(5, 3)

sales = pd.DataFrame(
    data,
    index=['Apples', 'Bananas', 'Milk', 'Bread', 'Eggs'],
    columns=['Week1', 'Week2', 'Week3']
)
sales

         Week1  Week2  Week3
Apples      10     11     12
Bananas     13     14     15
Milk        16     17     18
Bread       19     20     21
Eggs        22     23     24

In [ ]:

sales.loc['Butter'] = np.arange(10, 14)
sales

         Week1  Week2  Week3  Week4
Apples      10     11     12    NaN
Bananas     13     14     15    NaN
Milk        16     17     18    NaN
Bread       19     20     21    NaN
Eggs        22     23     24    NaN
Butter      10     11     12   13.0

In [ ]:
sales.loc['Cheese'] = np.nan
sales

         Week1  Week2  Week3  Week4
Apples    10.0   11.0   12.0    NaN
Bananas   13.0   14.0   15.0    NaN
Milk      16.0   17.0   18.0    NaN
Bread     19.0   20.0   21.0    NaN
Eggs      22.0   23.0   24.0    NaN
Butter    10.0   11.0   12.0   13.0
Cheese     NaN    NaN    NaN    NaN

In [ ]:
sales['Week5'] = np.nan
sales

         Week1  Week2  Week3  Week4  Week5
Apples    10.0   11.0   12.0    NaN    NaN
Bananas   13.0   14.0   15.0    NaN    NaN
Milk      16.0   17.0   18.0    NaN    NaN
Bread     19.0   20.0   21.0    NaN    NaN
Eggs      22.0   23.0   24.0    NaN    NaN
Butter    10.0   11.0   12.0   13.0    NaN
Cheese     NaN    NaN    NaN    NaN    NaN

In [ ]:

sales.loc['Apples', 'Week4'] = 18.0
sales

         Week1  Week2  Week3  Week4  Week5
Apples    10.0   11.0   12.0   18.0    NaN
Bananas   13.0   14.0   15.0    NaN    NaN
Milk      16.0   17.0   18.0    NaN    NaN
Bread     19.0   20.0   21.0    NaN    NaN
Eggs      22.0   23.0   24.0    NaN    NaN
Butter    10.0   11.0   12.0   13.0    NaN
Cheese     NaN    NaN    NaN    NaN    NaN

In [ ]:

sales.isnull()

         Week1  Week2  Week3  Week4  Week5
Apples   False  False  False  False   True
Bananas  False  False  False   True   True
Milk     False  False  False   True   True
Bread    False  False  False   True   True
Eggs     False  False  False   True   True
Butter   False  False  False  False   True
Cheese    True   True   True   True   True

In [ ]:
sales.notnull()

         Week1  Week2  Week3  Week4  Week5
Apples    True   True   True   True  False
Bananas   True   True   True  False  False
Milk      True   True   True  False  False
Bread     True   True   True  False  False
Eggs      True   True   True  False  False
Butter    True   True   True   True  False
Cheese   False  False  False  False  False

In [ ]:

sales.isnull().sum()

Week1    1
Week2    1
Week3    1
Week4    5
Week5    7
dtype: int64

In [ ]:
sales.isnull().sum().sum()

np.int64(15)

In [ ]:

sales.count()

Week1    6
Week2    6
Week3    6
Week4    2
Week5    0
dtype: int64

In [ ]:

sales.Week4[sales.Week4.notnull()]

Apples    18.0
Butter    13.0
Name: Week4, dtype: float64

In [ ]:

sales.Week4.dropna()

Apples    18.0
Butter    13.0
Name: Week4, dtype: float64

In [ ]:

sales.dropna()

Empty DataFrame
Columns: [Week1, Week2, Week3, Week4, Week5]
Index: []

In [ ]:

sales.dropna(how='all')

         Week1  Week2  Week3  Week4  Week5
Apples    10.0   11.0   12.0   18.0    NaN
Bananas   13.0   14.0   15.0    NaN    NaN
Milk      16.0   17.0   18.0    NaN    NaN
Bread     19.0   20.0   21.0    NaN    NaN
Eggs      22.0   23.0   24.0    NaN    NaN
Butter    10.0   11.0   12.0   13.0    NaN

In [ ]:

sales.dropna(how='all', axis=1)

         Week1  Week2  Week3  Week4
Apples    10.0   11.0   12.0   18.0
Bananas   13.0   14.0   15.0    NaN
Milk      16.0   17.0   18.0    NaN
Bread     19.0   20.0   21.0    NaN
Eggs      22.0   23.0   24.0    NaN
Butter    10.0   11.0   12.0   13.0
Cheese     NaN    NaN    NaN    NaN

In [ ]:

sales.dropna(thresh=5, axis=1)

         Week1  Week2  Week3
Apples    10.0   11.0   12.0
Bananas   13.0   14.0   15.0
Milk      16.0   17.0   18.0
Bread     19.0   20.0   21.0
Eggs      22.0   23.0   24.0
Butter    10.0   11.0   12.0
Cheese     NaN    NaN    NaN

In [ ]:
arr = np.array([100, 200, np.nan, 300])

series = pd.Series(arr)
arr.mean(), series.mean()

(np.float64(nan), np.float64(200.0))

In [ ]:
week4 = sales.Week4
week4.sum()

np.float64(31.0)

In [ ]:
week4.mean()

np.float64(15.5)

In [ ]:

week4.cumsum()

Apples     18.0
Bananas     NaN
Milk        NaN
Bread       NaN
Eggs        NaN
Butter     31.0
Cheese      NaN
Name: Week4, dtype: float64

In [ ]:

filled_sales = sales.fillna(0)
filled_sales

         Week1  Week2  Week3  Week4  Week5
Apples    10.0   11.0   12.0   18.0    0.0
Bananas   13.0   14.0   15.0    0.0    0.0
Milk      16.0   17.0   18.0    0.0    0.0
Bread     19.0   20.0   21.0    0.0    0.0
Eggs      22.0   23.0   24.0    0.0    0.0
Butter    10.0   11.0   12.0   13.0    0.0
Cheese     0.0    0.0    0.0    0.0    0.0

In [ ]:
sales.mean(numeric_only=True)

Week1    15.0
Week2    16.0
Week3    17.0
Week4    15.5
Week5     NaN
dtype: float64

In [ ]:

filled_sales.mean(numeric_only=True)

Week1    12.857143
Week2    13.714286
Week3    14.571429
Week4     4.428571
Week5     0.000000
dtype: float64

In [ ]:

sales.Week4.ffill()

Apples     18.0
Bananas    18.0
Milk       18.0
Bread      18.0
Eggs       18.0
Butter     13.0
Cheese     13.0
Name: Week4, dtype: float64

In [ ]:

sales.Week4.bfill()

Apples     18.0
Bananas    13.0
Milk       13.0
Bread      13.0
Eggs       13.0
Butter     13.0
Cheese      NaN
Name: Week4, dtype: float64

In [ ]:

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [ ]:

employees = pd.DataFrame({
    "Age":        [28, np.nan, 35, 41, 24],
    "Salary":     [42000, 55000, np.nan, 71000, 39000],
    "Department": ["Sales", "IT", "Sales", np.nan, "IT"],
})
employees

    Age   Salary Department
0  28.0  42000.0      Sales
1   NaN  55000.0         IT
2  35.0      NaN      Sales
3  41.0  71000.0        NaN
4  24.0  39000.0         IT

In [ ]:
mean_imputer = SimpleImputer(strategy="mean")

employees["Age_Mean"] = mean_imputer.fit_transform(employees[["Age"]]).ravel()
employees[["Age", "Age_Mean"]]

    Age  Age_Mean
0  28.0      28.0
1   NaN      32.0
2  35.0      35.0
3  41.0      41.0
4  24.0      24.0

In [ ]:

median_imputer = SimpleImputer(strategy="median")
employees["Salary_Median"] = median_imputer.fit_transform(employees[["Salary"]]).ravel()
employees[["Salary", "Salary_Median"]]

    Salary  Salary_Median
0  42000.0        42000.0
1  55000.0        55000.0
2      NaN        48500.0
3  71000.0        71000.0
4  39000.0        39000.0

In [ ]:

mode_imputer = SimpleImputer(strategy="most_frequent")
employees["Department_Mode"] = mode_imputer.fit_transform(employees[["Department"]]).ravel()
employees[["Department", "Department_Mode"]]

  Department Department_Mode
0      Sales           Sales
1         IT              IT
2      Sales           Sales
3        NaN              IT
4         IT              IT

In [ ]:
num_cols = ["Age", "Salary"]

mice_imputer = IterativeImputer(max_iter=10, random_state=42)

mice_result = employees[num_cols].copy()
mice_result.iloc[:, :] = mice_imputer.fit_transform(mice_result)

employees["Age_MICE"] = mice_result["Age"]
employees["Salary_MICE"] = mice_result["Salary"]

In [ ]:

employees

,Age,Salary,Department,Age_Mean,Salary_Median,Department_Mode,Age_MICE,Salary_MICE
0,28.0,42000.0,Sales,28.0,42000.0,Sales,28.000000,42000.00000
1,NaN,55000.0,IT,32.0,55000.0,IT,33.188021,55000.00000
2,35.0,NaN,Sales,35.0,48500.0,Sales,35.000000,58502.38757
3,41.0,71000.0,NaN,41.0,71000.0,IT,41.000000,71000.00000
4,24.0,39000.0,IT,24.0,39000.0,IT,24.000000,39000.00000