In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("bank.csv")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [2]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [4]:
df.head(20)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
5,42,management,single,tertiary,no,0,yes,yes,unknown,5,may,562,2,-1,0,unknown,yes
6,56,management,married,tertiary,no,830,yes,yes,unknown,6,may,1201,1,-1,0,unknown,yes
7,60,retired,divorced,secondary,no,545,yes,no,unknown,6,may,1030,1,-1,0,unknown,yes
8,37,technician,married,secondary,no,1,yes,no,unknown,6,may,608,1,-1,0,unknown,yes
9,28,services,single,secondary,no,5090,yes,no,unknown,6,may,1297,3,-1,0,unknown,yes
10,38,admin.,single,secondary,no,100,yes,no,unknown,7,may,786,1,-1,0,unknown,yes
11,30,blue-collar,married,secondary,no,309,yes,no,unknown,7,may,1574,2,-1,0,unknown,yes
12,29,management,married,tertiary,no,199,yes,yes,unknown,7,may,1689,4,-1,0,unknown,yes
13,46,blue-collar,single,tertiary,no,460,yes,no,unknown,7,may,1102,2,-1,0,unknown,yes
14,31,technician,single,tertiary,no,703,yes,no,unknown,8,may,943,2,-1,0,unknown,yes
15,35,management,divorced,tertiary,no,3837,yes,no,unknown,8,may,1084,1,-1,0,unknown,yes
16,32,blue-collar,single,primary,no,611,yes,no,unknown,8,may,541,3,-1,0,unknown,yes
17,49,services,married,secondary,no,-8,yes,no,unknown,8,may,1119,1,-1,0,unknown,yes
18,41,admin.,married,secondary,no,55,yes,no,unknown,8,may,1120,2,-1,0,unknown,yes
19,49,admin.,divorced,secondary,no,168,yes,yes,unknown,8,may,513,1,-1,0,unknown,yes

In [5]:
df.tail()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [6]:
df['balance'].dtype

dtype('int64')

In [7]:
df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
deposit      object
dtype: object

In [8]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [9]:
df.axes

[RangeIndex(start=0, stop=11162, step=1),
 Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
        'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
        'previous', 'poutcome', 'deposit'],
       dtype='object')]

In [10]:
df.ndim

2

In [11]:
df.size

189754

In [12]:
df.shape

(11162, 17)

In [13]:
df.values

array([[59, 'admin.', 'married', ..., 0, 'unknown', 'yes'],
       [56, 'admin.', 'married', ..., 0, 'unknown', 'yes'],
       [41, 'technician', 'married', ..., 0, 'unknown', 'yes'],
       ...,
       [32, 'technician', 'single', ..., 0, 'unknown', 'no'],
       [43, 'technician', 'married', ..., 5, 'failure', 'no'],
       [34, 'technician', 'married', ..., 0, 'unknown', 'no']],
      shape=(11162, 17), dtype=object)

In [14]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000

In [ ]:
df.max()

age               95
job          unknown
marital       single
education    unknown
default          yes
balance        81204
housing          yes
loan             yes
contact      unknown
day               31
month            sep
duration        3881
campaign          63
pdays            854
previous          58
poutcome     unknown
deposit          yes
dtype: object

In [16]:
df.min()

age                18
job            admin.
marital      divorced
education     primary
default            no
balance         -6847
housing            no
loan               no
contact      cellular
day                 1
month             apr
duration            2
campaign            1
pdays              -1
previous            0
poutcome      failure
deposit            no
dtype: object

In [ ]:
df.mean(numeric_only=True)

age           41.231948
balance     1528.538524
day           15.658036
duration     371.993818
campaign       2.508421
pdays         51.330407
previous       0.832557
dtype: float64

In [18]:
df.median(numeric_only=True)

age          39.0
balance     550.0
day          15.0
duration    255.0
campaign      2.0
pdays        -1.0
previous      0.0
dtype: float64

In [19]:
df.std(numeric_only=True)

age           11.913369
balance     3225.413326
day            8.420740
duration     347.128386
campaign       2.722077
pdays        108.758282
previous       2.292007
dtype: float64

In [20]:
df.sample(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
7479,30,management,single,tertiary,no,222,yes,no,cellular,12,aug,112,4,-1,0,unknown,no
4484,29,services,single,tertiary,no,1788,no,no,cellular,27,oct,353,1,-1,0,unknown,yes
9864,30,technician,married,secondary,no,394,no,no,cellular,22,aug,216,13,-1,0,unknown,no
514,31,management,married,tertiary,no,325,yes,no,cellular,18,jul,1139,2,-1,0,unknown,yes
8240,41,technician,married,secondary,no,-274,yes,no,unknown,27,may,182,3,-1,0,unknown,no

In [ ]:

df.dropna()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

In [22]:
df['job']

0             admin.
1             admin.
2         technician
3           services
4             admin.
            ...
11157    blue-collar
11158       services
11159     technician
11160     technician
11161     technician
Name: job, Length: 11162, dtype: object

In [23]:
df.job  # attribute-style access -- same result as df['job']

0             admin.
1             admin.
2         technician
3           services
4             admin.
            ...
11157    blue-collar
11158       services
11159     technician
11160     technician
11161     technician
Name: job, Length: 11162, dtype: object

In [24]:
print("Shape:", df.shape)
df.info()

Shape: (11162, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB

In [25]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
age,11162.0,NaN,NaN,NaN,41.231948,11.913369,18.0,32.0,39.0,49.0,95.0
job,11162,12,management,2566,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital,11162,3,married,6351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education,11162,4,secondary,5476,NaN,NaN,NaN,NaN,NaN,NaN,NaN
default,11162,2,no,10994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
balance,11162.0,NaN,NaN,NaN,1528.538524,3225.413326,-6847.0,122.0,550.0,1708.0,81204.0
housing,11162,2,no,5881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan,11162,2,no,9702,NaN,NaN,NaN,NaN,NaN,NaN,NaN
contact,11162,3,cellular,8042,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day,11162.0,NaN,NaN,NaN,15.658036,8.42074,1.0,8.0,15.0,22.0,31.0
month,11162,12,may,2824,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration,11162.0,NaN,NaN,NaN,371.993818,347.128386,2.0,138.0,255.0,496.0,3881.0
campaign,11162.0,NaN,NaN,NaN,2.508421,2.722077,1.0,1.0,2.0,3.0,63.0
pdays,11162.0,NaN,NaN,NaN,51.330407,108.758282,-1.0,-1.0,-1.0,20.75,854.0
previous,11162.0,NaN,NaN,NaN,0.832557,2.292007,0.0,0.0,0.0,1.0,58.0
poutcome,11162,4,unknown,8326,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deposit,11162,2,no,5873,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
cat_cols = df.select_dtypes(include='object').columns
unknown_pct = {c: round((df[c] == 'unknown').mean() * 100, 2) for c in cat_cols}
unknown_pct = {k: v for k, v in unknown_pct.items() if v > 0}
unknown_pct

{'job': np.float64(0.63),
 'education': np.float64(4.45),
 'contact': np.float64(21.02),
 'poutcome': np.float64(74.59)}

In [27]:
# Treat 'unknown' as missing
df_clean = df.replace('unknown', np.nan)
missing_pct = (df_clean.isnull().mean() * 100).sort_values(ascending=False)
missing_pct[missing_pct > 0]

poutcome     74.592367
contact      21.017739
education     4.452607
job           0.627128
dtype: float64

In [28]:
# Rule of thumb (same as the housing example): drop columns missing more than 15% of their data
drop_threshold = 15
cols_to_drop = missing_pct[missing_pct > drop_threshold].index.tolist()
print("Dropping (too much missing):", cols_to_drop)
df_clean = df_clean.drop(columns=cols_to_drop)

Dropping (too much missing): ['poutcome', 'contact']

In [29]:
# Remaining missing values are low (<5%) -> impute categoricals with the mode
remaining_missing = df_clean.isnull().sum()
remaining_missing = remaining_missing[remaining_missing > 0]
print(remaining_missing)

for col in remaining_missing.index:
    mode_val = df_clean[col].mode()[0]
    df_clean[col] = df_clean[col].fillna(mode_val)

print("\nMissing values left:", df_clean.isnull().sum().sum())

job           70
education    497
dtype: int64

Missing values left: 0

In [30]:
df_clean['was_contacted_before'] = (df_clean['pdays'] != -1).astype(int)
df_clean[['pdays', 'was_contacted_before']].head()

   pdays  was_contacted_before
0     -1                     0
1     -1                     0
2     -1                     0
3     -1                     0
4     -1                     0

In [31]:
dupe_count = df_clean.duplicated().sum()
print("Duplicate rows found:", dupe_count)
df_clean = df_clean.drop_duplicates()
print("Shape after dropping duplicates:", df_clean.shape)

Duplicate rows found: 0
Shape after dropping duplicates: (11162, 16)

In [32]:
df_clean = df_clean.drop(columns=['duration'])
df_clean.columns.tolist()

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'day',
 'month',
 'campaign',
 'pdays',
 'previous',
 'deposit',
 'was_contacted_before']

In [33]:
for col in df_clean.select_dtypes(include='object').columns:
    df_clean[col] = df_clean[col].str.strip().str.lower()

df_clean['deposit'] = df_clean['deposit'].map({'yes': 1, 'no': 0})
df_clean[['deposit']].value_counts()

deposit
0          5873
1          5289
Name: count, dtype: int64

In [35]:
Q1 = df_clean['balance'].quantile(0.25)
Q3 = df_clean['balance'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outlier_count = ((df_clean['balance'] < lower) | (df_clean['balance'] > upper)).sum()
print(f"Outliers in balance: {outlier_count} ({outlier_count/len(df_clean)*100:.1f}%)")

# Cap rather than delete -- keeps the rows, limits the extreme skew
df_clean['balance'] = df_clean['balance'].clip(lower=lower, upper=upper)

Outliers in balance: 1055 (9.5%)

In [36]:
cat_cols_final = df_clean.select_dtypes(include='object').columns
df_clean[cat_cols_final] = df_clean[cat_cols_final].astype('category')
df_clean.dtypes

age                        int64
job                     category
marital                 category
education               category
default                 category
balance                    int64
housing                 category
loan                    category
day                        int64
month                   category
campaign                   int64
pdays                      int64
previous                   int64
deposit                    int64
was_contacted_before       int64
dtype: object

In [37]:
print("Final shape:", df_clean.shape)
df_clean.head()

Final shape: (11162, 15)

,age,job,marital,education,default,balance,housing,loan,day,month,campaign,pdays,previous,deposit,was_contacted_before
0,59,admin.,married,secondary,no,2343,yes,no,5,may,1,-1,0,1,0
1,56,admin.,married,secondary,no,45,no,no,5,may,1,-1,0,1,0
2,41,technician,married,secondary,no,1270,yes,no,5,may,1,-1,0,1,0
3,55,services,married,secondary,no,2476,yes,no,5,may,1,-1,0,1,0
4,54,admin.,married,tertiary,no,184,no,no,5,may,2,-1,0,1,0

In [38]:
df_clean.to_csv("bank_cleaned.csv", index=False)
print("Saved bank_cleaned.csv")

Saved bank_cleaned.csv